import type { Metadata } from "next";
import "@App/_styles/globals.css";
import "@App/_styles/animation.css";
import ProviderClerk from "@/contexts/providers/Clerk";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";


export const metadata: Metadata = {
  title: "CloudDocs",
  keywords: ["cloud", "docs", "nextjs", "clerk", "authentication"],
  authors: [{ name: "dangvanthangdvt09@gmail.com", url: "https://yourwebsite.com" }],
  creator: "dang van thang",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="mdl-js"> 
        <body>
          <ProviderClerk>
            {children}
          </ProviderClerk>
        </body>
      </html>
  );
}
