import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-tiptap/styles.css";

const kanit = Kanit({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-kanit',
});

export const metadata: Metadata = {
  title: "Create google doc clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} font-sans antialiased min-h-screen flex flex-col`}>
        <div className="flex-1">
          {children}
        </div>
      </body>
    </html>
  );
}
